
📖[プロを目指す人のためのRuby入門［改訂2版］ 言語仕様からテスト駆動開発・デバッグ技法まで](https://gihyo.jp/book/2021/978-4-297-12437-3)

#### さまざまな繰り返し処理（つづき）

- for文
  eachメソッドを定義しているオブジェクトに対して繰り返し処理を行える。
  ```ruby
  for 変数 in 配列やハッシュ
    繰り返し処理
  end
  ```
  for文は、eachメソッドとは違って、配列の要素を受け取る変数や、for文の中で作成したローカル変数をfor文の外でも使うことができる。
  しかし、Rubyで繰り返し処理を行うときは、eachやmapなどの繰り返し処理用のメソッドを使うことが多い。

- loopメソッド
  あえて無限ループを作りたいときには、`loop`メソッドを使うという方法がある。
  ```ruby
  loop do
    無限ループ用処理
  end
  ```
  無限ループから脱出するときには`break`を使う。
  `loop`はブロックを使うのでブロック内の変数をブロックの外（ループの外）で参照することはできないが、while文はループの外でも変数を参照できる。

- 再帰呼び出し
  あるメソッドの中でそのメソッド自身をもう一度呼び出すこと。
  一種の繰り返し処理として使うことができる。

#### 繰り返し処理用の制御構造

ループを脱出するためのキーワードには、`break`以外に`next`、`redo`がある。
また、Kernelモジュールの`throw`メソッドと`catch`メソッドも`break`と同じような用途で使われる。
- break
  繰返しを脱出できる。`each`,`while`,`until`,`for`などで使える。
  `break`に引数を渡すと`while`文や`for`文の戻り値になる。引数を渡さないときはnilになる。
  繰り返し処理が入れ子になっている時は、**一番内側の繰り返し処理**を脱出する。

- throwとcatchを使った大域脱出
  一気に外側のループまで脱出したいときは、Kernelモジュールのthrowとcatchメソッドを使う。
  ```ruby
  catch タグ do # タグには通常シンボルを使う。
    繰り返し処理
    throw タグ # すべての繰り返し処理を脱出。
  end
  ```
  throw、catchはほかの言語（JSとか…）だと例外処理につあくぁれる場合があるが、Rubyの場合は例外処理とは関係ない。（混乱する！）
  Rubyの例外処理にはraiseとrescueを使う。
  throw、catchのタグが一致してないとエラーが派生する。throwの第二引数を渡すと、catchの戻り値になる。
  繰り返し処理と無関係に利用できるが、だいたいは繰り返し処理の大域脱出で使われることがおおい。

  
